name: cxr-vlm-interp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - tqdm
  - ipykernel
  - jupyterlab
  - scikit-learn
  - scipy
  - joblib
  - matplotlib
  - seaborn
  - pillow
  - h5py
  - pip:
      - "transformers>=4.50.0"
      - accelerate
      - huggingface-hub
      - safetensors
      - sentencepiece
      - protobuf
      - torch
      - torchvision
